version: '3.8'

services:
  bot:
    build: .
    container_name: wetero_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - CHANNEL_ID=${CHANNEL_ID}
      - PROMO_CHANNEL_ID=${PROMO_CHANNEL_ID}
      - DATA_DIR=/app/shared
    volumes:
      - ./shared:/app/shared
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
